image: node:16-alpine3.14

pages:
  stage: deploy
  before_script:
    - yarn global add sperm
    - chmod +x ./build.sh
  script:
    - ./build.sh
  artifacts:
    paths:
      - public
  only:
    - master
